### ISSUE TITLE
Eufy X9 Pro

### ISSUE THREAD

**Issue by john500y2k** [CodeFoodPixels/robovac#4] opened 2023-08-11 15:55 UTC
Would it be possible to add support for the Eufy X9 Pro T2320 model?

**Comment by fbricker** [comment] 2023-08-15 02:30
I also have one Eufy Robovac X9 Pro. It would be great to have this working 🙏

**Comment by john500y2k** [comment] 2023-08-15 07:41
> I also have one Eufy Robovac X9 Pro. It would be great to have this working 🙏
> 
> I tried adding the T2320 model to the "X": [ .... ] array like this:
> 
> ```
> ...
>         "T2255",
>     ],
>     "X": ["T2261", "T2262", "T2320"],
> }
> ...
> ```
> 
> And I got the device recognized...
> 
> <img alt="Screenshot 2023-08-14 at 23 50 39" width="1045" src="https://user-images.githubusercontent.com/1865352/260615606-46999c9a-e82e-49f1-911e-24f46c6cc108.png"> <img alt="Screenshot 2023-08-14 at 23 50 49" width="669" src="https://user-images.githubusercontent.com/1865352/260615619-1fb77e25-443d-4ab8-bef7-9c6013e584db.png">
> But it always displays status error and start / stop buttons don't do anything.
> 
> If you someone has an idea, I can try it :)

I also did the same added T2320 there and also in the has map features setting.

Results in the same as you are seeing error with no responses from controls.

**Comment by CodeFoodPixels** [comment] 2023-08-15 11:27
Have you set the IP of the device?

**Comment by CodeFoodPixels** [comment] 2023-08-15 13:01
X9 Pro has been added in [f4e4a64](https://github.com/CodeFoodPixels/robovac/commit/f4e4a647ef4ac011a38c42f5c91bc5ecde122dbb)

**Comment by fbricker** [comment] 2023-08-15 22:31
Same here... removed and re-installed from main instead of 1.0.0 (the added T2320 code is in there).

Logged in with my Eufy account, it finds the robot and ask me for it's room.

Then I click configure, set the IP (get a confirmation message)

But I still get status error 😭 

<img width="1512" alt="Screenshot 2023-08-15 at 19 28 11" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/12c89620-de5a-499f-8585-9de31e6287c7">

<img width="1512" alt="Screenshot 2023-08-15 at 19 28 46" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/b39a4260-8455-464b-a7bb-e526be7d5fec">

Buttons are also not working 😢

**Comment by CodeFoodPixels** [comment] 2023-08-17 21:59
@fbricker this sounds like it hasn't got an IP address. I've just added autodiscovery in main, so if you redownload from main, you won't need to input the IP yourself

**Comment by fbricker** [comment] 2023-08-20 15:07
Hi, I tried that... but still have the error (before I set the IP i get an error saying I don't have the IP set, and after setting it just says error: unknown)

Here are the steps I follow:


**First I installed the plugin from Main and configured by adding the credentials.**

<img width="745" alt="Screenshot 2023-08-20 at 11 50 00" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/6c55789f-5015-473e-970b-61c52bd6d460">
.
.



**Get the device added**

<img width="1512" alt="Screenshot 2023-08-20 at 11 50 26" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/c9d41981-d729-43bd-b36b-97a229d84863">
.
.



**Check the "IP Address not set" error**

<img width="1512" alt="Screenshot 2023-08-20 at 11 50 59" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/d3088937-a817-408e-936a-ec07524f706b">
.
.



**Validate the IP on the router**

![IMG_9413](https://github.com/CodeFoodPixels/robovac/assets/1865352/1a02c3ee-7063-40b1-86ae-d5f6d7913c90)
.
.



**Configure the IP**

<img width="1512" alt="Screenshot 2023-08-20 at 11 51 16" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/dc5dbe84-b387-4f12-b22a-5a98e351e67f">
.
.



**Get the success message**

<img width="1512" alt="Screenshot 2023-08-20 at 11 51 22" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/82ec01b4-ff77-42a4-833e-b1391bfb9fa0">
.
.


**Check the status again...**

<img width="1512" alt="Screenshot 2023-08-20 at 11 51 43" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/d292b22c-a4fa-4e5a-9a47-6a84d9409dc5">


Please let me know if there's any other test you'll like me to perform.

**Comment by CodeFoodPixels** [comment] 2023-08-21 16:09
> > X9 Pro has been added in [f4e4a64](https://github.com/CodeFoodPixels/robovac/commit/f4e4a647ef4ac011a38c42f5c91bc5ecde122dbb)
> 
> Thanks so much, really appreciate your support and efforts. Have redownloaded and tried out the revisions, also confirmed setting the IP of the device which was successful. However still getting the following errors.
> 
> ```
> 2023-08-15 16:06:47.828 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'gwId': 'bf7e482efae9e7b687zijq', 'devId': 'bf7e482efae9e7b687zijq'}, 699224, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> 
> 2023-08-15 16:06:47.855 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'dps': {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 59}}, 699224, None)
> 
> 2023-08-15 16:06:47.855 INFO (MainThread) [custom_components.robovac.tuyalocalapi] Received updated state bf7e482efae9e7b687zijq (192.168.0.232:6668): {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 59}
> 
> 2023-08-15 16:06:47.903 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> 
> 2023-08-15 16:06:47.957 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> 
> 2023-08-15 16:08:57.926 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> 
> 2023-08-15 16:08:57.995 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> 
> 2023-08-15 16:08:57.926 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> 
> 2023-08-15 16:08:57.995 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> 
> 2023-08-15 16:09:07.835 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'gwId': 'bf7e482efae9e7b687zijq', 'devId': 'bf7e482efae9e7b687zijq'}, 839231, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> 
> 2023-08-15 16:09:07.929 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> 
> 2023-08-15 16:09:07.931 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'dps': {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 60}}, 839231, None)
> 
> 2023-08-15 16:09:07.932 INFO (MainThread) [custom_components.robovac.tuyalocalapi] Received updated state bf7e482efae9e7b687zijq (192.168.0.232:6668): {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 60}
> 
> 2023-08-15 16:09:07.946 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> ```

None of these are errors, some of them are debug messages and should only show up if you have debug logging enabled.

**Comment by john500y2k** [comment] 2023-08-21 16:32
> > > X9 Pro has been added in [f4e4a64](https://github.com/CodeFoodPixels/robovac/commit/f4e4a647ef4ac011a38c42f5c91bc5ecde122dbb)
> > 
> > 
> > Thanks so much, really appreciate your support and efforts. Have redownloaded and tried out the revisions, also confirmed setting the IP of the device which was successful. However still getting the following errors.
> > ```
> > 2023-08-15 16:06:47.828 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'gwId': 'bf7e482efae9e7b687zijq', 'devId': 'bf7e482efae9e7b687zijq'}, 699224, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> > 
> > 2023-08-15 16:06:47.855 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'dps': {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 59}}, 699224, None)
> > 
> > 2023-08-15 16:06:47.855 INFO (MainThread) [custom_components.robovac.tuyalocalapi] Received updated state bf7e482efae9e7b687zijq (192.168.0.232:6668): {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 59}
> > 
> > 2023-08-15 16:06:47.903 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> > 
> > 2023-08-15 16:06:47.957 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> > 
> > 2023-08-15 16:08:57.926 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> > 
> > 2023-08-15 16:08:57.995 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> > 
> > 2023-08-15 16:08:57.926 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> > 
> > 2023-08-15 16:08:57.995 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> > 
> > 2023-08-15 16:09:07.835 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'gwId': 'bf7e482efae9e7b687zijq', 'devId': 'bf7e482efae9e7b687zijq'}, 839231, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> > 
> > 2023-08-15 16:09:07.929 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, <Device bf7e482efae9e7b687zijq (192.168.0.232:6668)>)
> > 
> > 2023-08-15 16:09:07.931 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0xa, {'dps': {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 60}}, 839231, None)
> > 
> > 2023-08-15 16:09:07.932 INFO (MainThread) [custom_components.robovac.tuyalocalapi] Received updated state bf7e482efae9e7b687zijq (192.168.0.232:6668): {'151': True, '156': True, '158': 'Max', '159': True, '160': False, '161': 70, '163': 60}
> > 
> > 2023-08-15 16:09:07.946 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bf7e482efae9e7b687zijq (192.168.0.232:6668): Message(0x9, b'', 0, None)
> > ```
> 
> None of these are errors, some of them are debug messages and should only show up if you have debug logging enabled.

Ah sorry you are correct I did enable debug logging at the time.

Have seen your posts regarding the latest release:

https://github.com/CodeFoodPixels/robovac/releases/tag/v1.1.0.beta.1

Have used that version and encountered the below errors:

When setting up just using Eufy login credentials (no manual IP entry)
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",line 362, in _async_setup_platform await asyncio.shield(task)
File "/config/custom_components/robovac/vacuum.py", line 110, in async_setup_entry await entity.vacuum. async_connect ()
File "/config/custom_components/robovac/tuyalocalapi.py", line 678, in async_connect
sock.connect ((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
```

After manually entering IP:
```
/config/custom_components/robovac/__init._….py:85:RuntimeWarning:coroutine'ConfigEntries.async_reload'wasneverawaited hass.config_entries.async_reload(entry.entry_id)
``` 

After reloading integration post manual IP config:
```
Incomplete read from: bf8374esie9e7b027zig (192.168.0.69:6668) : 0 bytes read on a total of undefined expected bytes
``` 

So sorry for the wide array of errors during the different stages/attempts of setting up, but am really hoping that sort of detail assists you more in understanding what is occurring.

Thank you so much for all of your efforts, really appreciate it so much :)

**Comment by fbricker** [comment] 2023-08-23 05:42
Hi thx, for all your efforts :) I still have the same even with beta.1

I think that in order for the discovery to work propperly, I need to disable the TuyaLocal integration I have due to some port conflicts. I don't think this is the cause of the issue anyway. Buy maybe it helps for other cases.

Here goes the logs I had before disabling the tuyalocal integration:

<img width="1428" alt="Screenshot 2023-08-23 at 02 21 58" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/d85ec9e9-4585-4bee-bd61-92a49c85fdb9">
<img width="922" alt="Screenshot 2023-08-23 at 02 31 47" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/f606988a-6e06-4521-b509-bc0aa3406c94">

Once I managed to get the disvoery working, I still have the error on the robot
<img width="1153" alt="Screenshot 2023-08-23 at 02 35 13" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/a84f09b9-bcb9-44e2-a097-f82142663244">

<img width="1442" alt="Screenshot 2023-08-23 at 02 36 29" src="https://github.com/CodeFoodPixels/robovac/assets/1865352/cdffecbe-3b90-4843-b4f8-a8a1eaeafc03">

This time it displays less fields... but still displays unavailable.

Maybe this model changed something in the protocol or the port is different?

Thx again!

**Comment by fbricker** [comment] 2023-08-30 22:11
Hi, sorry to bother you again. Do you have something you want me to try? Can I help somehow?

**Comment by CodeFoodPixels** [comment] 2023-08-31 10:20
So this is indeed a conflict with the TuyaLocal integration, they don't allow port reuse, and both integrations try to listen on the same port. I've submitted a PR to that integration.

Could you give [v1.1.0.beta.2](https://github.com/CodeFoodPixels/robovac/releases/tag/v1.1.0.beta.2) a try with the TuyaLocal integration disabled please?

**Comment by john500y2k** [comment] 2023-09-01 15:59
Saw your updates and have given them a try.

Beta 2:
Account added successfully but device not discovered. Log outputs errors below

```
Logger: homeassistant.components.vacuum
Source: custom_components/robovac/tuyalocalapi.py:678
Integration: Vacuum (documentation, issues)
First occurred: 4:45:19 pm (1 occurrences)
Last logged: 4:45:19 pm

Error while setting up robovac platform for vacuum

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",line 362, in _async_setup_platform await asyncio.shield(task)
File "/config/custom_components/robovac/vacuum.py", line 110, in async_setup_entry
await entity. vacuum. async_connect ()
File "/config/custom_components/robovac/tuyalocalapi.py", line 678, in async_connect
sock.connect ((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
```

Beta 3:
Account added successfully and device discovered successfully however just reports unavailable and there are no errors being reported in the logs.

Logs from debug option
```
2023-09-01 16:34:07.223 DEBUG (MainThread) [custom_components. robovac. tuyalocalapil Disconnected from [redacted] (192.168.0.232:6668)
2023-09-01 16:34:07.229 DEBUG (MainThread) [custom_components. robovac. tuyalocalapil Connecting to [redacted] (192.168.0.232:6668)
2023-09-01 16:34:07.347 DEBUG (MainThread) [custom_components.robovac.tuyalocalapil Sending to [redacted] (192.168.0.232:6668) :
Message (Oxa, {'gwId': '[redacted]', 'devId': '[redacted]'}, 312926, «Device [redacted] (192.168.0.232:6668)>)
2023-09-01 16:34:07.353 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from [redacted]
(192.168.0.232:6668) : Message (Oxa, {'dps':
{'151': True, '156': True, '158': 'Turbo
'159': True, '160': False,
'161': 70, '163': 100}}, 312926,
None)
2023-09-01 16:34:07.354 INFO (MainThread) [custom components. robovac. tuyalocalapi] Received updated state [redacted]
(192.168.0.232:6668): {'151': True,
"156': True,
'158': 'Turbo', '159': True, '160': False,
"161': 70, '163': 100}
2023-09-01 16:34:27.359 DEBUG (MainThread) [custom_components. robovac. tuyalocalapil Sending to [redacted] (192.168.0.232:6668) :
Message (Oxa, {'gwId': '[redacted]', 'devId': '[redacted]'}, 333056, «Device [redacted] (192.168.0.232:6668)>)
2023-09-01 16:34:27.415 DEBUG (MainThread) [custom_components. robovac. tuyalocalapi] Received message from [redacted]
(192.168.0.232:6668) : Message (0xa, {'dps': {'151': True, '156': True, '158': 'Turbo'
'159': True,
'160': False, '161': 70, '163': 100}3, 333056,
None)
2023-09-01 16:34:27.415 INFO (MainThread) [custom components.robovac.tuvalocalapi] Received updated state [redacted] (192.168.0.232:6668): {'151': True, '156': True,
2023-09-01 16:34:47.360 DEBUG (MainThread) [custom_components. robovac. tuyalocalapi] Sending to [redacted] (192.168.0.232:6668) :
Message (Oxa, {'gwId': '[redacted]', 'devId': '[redacted]'}, 353057, «Device [redacted] (192.168.0.232:6668)>)
2023-09-01 16:34:47.488 DEBUG (MainThread) [custom_components. robovac. tuyalocalapil Received message from [redacted]
(192.168.0.232:6668) : Message (Oxa, {'dps': {'151': True, '156': True,
'158': "Turbo'
'159': True,
'160': False, '161': 70, '163': 100}}, 353057,
None)
2023-09-01 16:34:47.488 INFO (MainThread) [custom_ components.robovac.tuyalocalapi] Received updated state [redacted] (192.168.0.232:6668): {'151': True, '156': True,
'158': 'Turbo', '159': True, '160: False, '161': 70, '163': 100}
```

Hope any of that is of value?

**Comment by CodeFoodPixels** [comment] 2023-09-06 10:07
@john500y2k Could you give beta 4 a try please?

@fbricker Beta 4 allows you to manually set the IP again, so please give that a try

**Comment by john500y2k** [comment] 2023-09-07 10:06
> @john500y2k Could you give beta 4 a try please?
> 
> @fbricker Beta 4 allows you to manually set the IP again, so please give that a try

Tried out beta 4, sadly still the same. Can add account and vacuum is auto discovered correctly but device remains unavailable with attribute error reported as “unknown” and no errors reported in the logs. Debug logging remains the same as my previous post. Also tried manually setting IP (auto discovery already had correct IP) but still the same.

Thanks so much for your perseverance it really is appreciated, please do let me know if there is anything I can try out on my end to help you understand where it’s having troubles.

My very limited trials with local Tuya was managing to connect however there was hardly any functionality (no way to start/stop a clean and so on) and the reported dps items were only the ones that are in the debug log which I have managed to figure out some of:

151: 
156: Auto-Return Cleaning
158: Fan Speed (quiet,standard,turbo,max)
159: Boost IQ
160: 
161: Voice Level
163: Battery Status

For the above I was able to successfully control the ones that can be via local Tuya and the changes were reflected on the robot and in Eufy app. Also updates were reflected in the integration on status updates or changes made via the Eufy app.

**Comment by CodeFoodPixels** [comment] 2023-09-14 11:26
@john500y2k I've discovered that one of the tuya apis returns a schema that I can potentially use for commands. Could you please run this and paste the output here? https://replit.com/@CodeFoodPixels/robovac-auth-test

**Comment by john500y2k** [comment] 2023-09-18 11:05
> @john500y2k I've discovered that one of the tuya apis returns a schema that I can potentially use for commands. Could you please run this and paste the output here? https://replit.com/@CodeFoodPixels/robovac-auth-test

Oh nice, have ran with output below:

```
********** Robovac Auth Tester **********
Logging in to Eufy
    Success
Getting Eufy device info
    Success
Devices
    Cleaning device: RoboVac X9 Pro (redacted)
        Found device in tuya
            RoboVac X9 Pro
            [{"attr":0,"canTrigger":true,"code":"proto","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":150,"mode":"rw","name":"协议","property":{"type":"string","maxlen":255},"type":"obj"},{"attr":0,"canTrigger":true,"code":"power","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":151,"mode":"rw","name":"电源开关","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"mode_ctrl","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":152,"mode":"rw","name":"模式控制","type":"raw"},{"attr":0,"canTrigger":true,"code":"work_status","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":153,"mode":"rw","name":"工作状态","type":"raw"},{"attr":0,"canTrigger":true,"code":"clean_params","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":154,"mode":"rw","name":"清洁参数","type":"raw"},{"attr":0,"canTrigger":true,"code":"remote_ctrl","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":155,"mode":"rw","name":"遥控方向","property":{"range":["Brake","Forward","Back","Left","Right"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"pause_job","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":156,"mode":"rw","name":"断点续扫","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"dnd","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":157,"mode":"rw","name":"勿扰","type":"raw"},{"attr":0,"canTrigger":true,"code":"suction_level","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":158,"mode":"rw","name":"吸力档位","property":{"range":["Quiet","Standard","Turbo","Max"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"boost_iq","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":159,"mode":"rw","name":"BoostIQ","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"calling_robot","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":160,"mode":"rw","name":"寻找机器人","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"volume","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":161,"mode":"rw","name":"音量","property":{"unit":"","min":0,"max":100,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"user_language","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":162,"mode":"rw","name":"语言管理","type":"raw"},{"attr":0,"canTrigger":true,"code":"bat_level","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":163,"mode":"ro","name":"电池电量","property":{"unit":"","min":0,"max":100,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"timing","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":164,"mode":"rw","name":"定时","type":"raw"},{"attr":0,"canTrigger":true,"code":"reserved2","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":165,"mode":"rw","name":"预留2","type":"raw"},{"attr":0,"canTrigger":true,"code":"log_debug","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":166,"mode":"rw","name":"调试设置","type":"raw"},{"attr":0,"canTrigger":true,"code":"clean_statistics","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":167,"mode":"rw","name":"清洁统计","type":"raw"},{"attr":0,"canTrigger":true,"code":"consumables","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":168,"mode":"rw","name":"耗材","type":"raw"},{"attr":0,"canTrigger":true,"code":"app_dev_info","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":169,"mode":"rw","name":"App和设备","type":"raw"},{"attr":0,"canTrigger":true,"code":"map_edit","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":170,"mode":"rw","name":"地图编辑","type":"raw"},{"attr":0,"canTrigger":true,"code":"multi_maps_ctrl","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":171,"mode":"rw","name":"多地图控制","type":"raw"},{"attr":0,"canTrigger":true,"code":"multi_maps_mng","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":172,"mode":"rw","name":"多地图管理","type":"raw"},{"attr":0,"canTrigger":true,"code":"station","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":173,"mode":"rw","name":"基站","type":"raw"},{"attr":0,"canTrigger":true,"code":"media_manager","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":174,"mode":"rw","name":"媒体管理","type":"raw"},{"attr":0,"canTrigger":true,"code":"reserved3","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":175,"mode":"rw","name":"预留3","property":{"type":"string","maxlen":255},"type":"obj"},{"attr":0,"canTrigger":true,"code":"unisetting","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":176,"mode":"rw","name":"公共设置","type":"raw"},{"attr":0,"canTrigger":true,"code":"error_warning","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":177,"mode":"rw","name":"故障提醒","type":"raw"},{"attr":0,"canTrigger":true,"code":"toast","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":178,"mode":"rw","name":"提示","type":"raw"},{"attr":0,"canTrigger":true,"code":"analysis","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":179,"mode":"rw","name":"数据分析","type":"raw"}]
Test script ran successfully
```

**Comment by CodeFoodPixels** [comment] 2023-09-29 17:09
Closing this in favour of #28

**Closed by CodeFoodPixels** 2023-09-29 17:09 UTC
